version: '2'

services:
  ayanami:
    env_file: ./secrets.env
    links:
      - redis
      - mysql
      - graphite
    command: >
                 bash -lc "./wait-for-it.sh -t 300 redis:6379; ./wait-for-it.sh -t 300 mysql:3306;
                 rake db:check || rake db:create db:structure:load;
                 rake db:migrate;
                 rails runner 'HeatWeaponCacheJob.perform_later';
                 bundle exec sidekiq -d -C config/sidekiq.yml;
                 passenger start"
    restart: unless-stopped
    build: .
    ports:
      - "127.0.0.1:3456:3000"
  mysql:
    env_file: ./secrets.env
    image: mysql
    entrypoint: /entrypoint.sh
    command: mysqld
    restart: unless-stopped
    ports:
      - "127.0.0.1:13306:3306"
    volumes:
      - /srv/ayanami/mysql:/var/lib/mysql
  redis:
    volumes:
      - redis-data:/data
    image: redis
    restart: unless-stopped
    command: redis-server --save 60 1000
  noxus:
    restart: unless-stopped
    env_file: ./secrets.env
    links:
      - mysql
    build: noxus
    ports:
      - "127.0.0.1:3457:80"
  graphite:
    restart: unless-stopped
    image: hopsoft/graphite-statsd
    ports:
      - "127.0.0.1:33456:80"
    volumes:
      - graphite-data:/opt/graphite/storage

volumes:
  graphite-data:
    external: false
  redis-data:
    external: false
  mysql-data:
    external: false
