version: '2'


services:
  ayanami:
    env_file: ./secrets.env
    depends_on:
      - redis
      - mysql
    command: >
                 bash -lc "./wait-for-it.sh -t 300 redis:6379; ./wait-for-it.sh -t 300 mysql:3306;
                 rake db:check || rake db:create db:structure:load;
                 rake db:migrate;
                 ./bin/rails runner 'CacheHeater.run';
                 unicorn -c config/unicorn.rb"
    restart: always
    build: .
    ports:
      - "127.0.0.1:3456:8080"
  mysql:
    env_file: ./secrets.env
    image: mysql
    entrypoint: /entrypoint.sh
    command: mysqld
    ports:
      - "127.0.0.1:13306:3306"
    volumes:
      - /srv/ayanami/mysql:/var/lib/mysql
  redis:
    image: redis