version: '2'
services:
  ayanami-production:
  # production DB is still not dockerized for me :(
  # service still requires you (or capistrano) to put proper database.yml
    depends_on:
      - ayanami-redis
    entrypoint: >
      bash -lc "./wait-for-it.sh ayanami-redis:6379; ./wait-for-it.sh";
      bash -lc "ayanami-mysql:3306 rake db:exists || rake db:create db:structure:load";
      bash -lc "./bin/rails runner 'CacheHeater.run'";
      bash -lc "unicorn -c config/unicorn.rb"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "127.0.0.1:3456:8080"
    working_dir: /ayanami
    #command: ./bin/rails server -b 0.0.0.0
  ayanami-mysql:
  build:
    context: .
    dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vae2Iex8jie5Uich
      - MYSQL_DATABASE=ayanami
  ayanami-redis:
    image: redis
