
development:
  adapter: mysql2
  encoding: utf8
  pool: 10
  reconnect: false
  database: steam-dev
  username: csgods
  password: tolop0Quuchohke8
  host: 127.0.0.1

docker:
  adapter: mysql2
  encoding: utf8
  pool: 10
  reconnect: false
  database: ayanami
  username: root
  password: vae2Iex8jie5Uich
  host: ayanami-mysql

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: 10
  reconnect: false
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: mysql
